### ISSUE TITLE
travis-solo does not work with pip --use-mirrors

### ISSUE THREAD

**Issue by thedrow** [jstasiak/travis-solo#6]
Here's the gist with the log https://gist.github.com/thedrow/5745691

**Comment by jstasiak** [comment]
Hmm, I just built https://github.com/thedrow/nose2-testsuite project and it worked fine.
Can you provide output of the following commands?

```
virtualenv --version
/home/omer/Documents/Projects/Python/nose2-testsuite/.travis-solo/2.7/bin/pip --version
```

**Comment by thedrow** [comment]
Nevermind. It was my mistake completely.

**Comment by jstasiak** [comment]
No problem, hope it works well for you now :)
