### ISSUE TITLE
Parallel testing with setuptools

### ISSUE THREAD

**Issue by myint** [jstasiak/travis-solo#9]
Running in parallel works fine for my projects that use plain `distutils`. But I noticed that it can fail when used with `setuptools` (during the `./setup.py install` step).

``` bash
$ travis-solo -j0
...
error: build/bdist.macosx-10.6-x86_64/egg/autopep8.py: No such file or directory
error: build/bdist.macosx-10.6-x86_64/egg: No such file or directory
...
```

I'll need to find out if the `build` directory can be overridden (for purposes of avoiding name collision).

**Comment by myint** [comment]
I found a workaround (hhatto/autopep8@1c895989422b0a02a32a4383a3f0467b44f20663).

**Comment by myint** [comment]
I was hoping to find a way to somehow override the default `build` directory via environment variable. But I didn't see any such thing in the `distutils`/`setuptools` source code. Perhaps the best we can do is document this in the readme.

**Comment by jstasiak** [comment]
I went quickly through distutils/setuptools source code and haven't found anything helpful either so yes, I'd say readme note is the way to go here.
